import bluetooth
import socket
import select
name="bt_server"
target_name="test"  # some random uuid, generated by https://www.famkruithof.net/uuid/uuidgen
uuid="B62C4E8D-62CC-404b-BBBF-BF3E3BBB1374"
import signal
#signal.signal(signal.SIGINT, signal.SIG_DFL)
def connect():
    serverSocket = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
    port = bluetooth.PORT_ANY
    serverSocket.bind(("", port))
    print("Listening for connections on port: ", port)  # wait for a message to be sent to this socket only once
    serverSocket.listen(1)
    bluetooth.advertise_service(serverSocket, "SampleServer",
                                service_id=uuid,
                                service_classes=[uuid, bluetooth.SERIAL_PORT_CLASS],
                                profiles=[bluetooth.SERIAL_PORT_PROFILE]
                                )
    inputSocket, address = serverSocket.accept()
    print("Got connection with", address)

    return inputSocket

def senddata(socket):
    nfile = input("Input path to the file: ")
    #index = path.rindex('/')  # индекс последней точки
   # nfile = path[index+1:len(path)]
    file = open(nfile, "r")
    data = file.read()
    file.close()
    print(data)
    if len(nfile) < 256:
        while len(nfile) != 256:
            nfile += " "

    socket.send(nfile)
    socket.send(data)
    print("Data is sent")

def recvdata(socket):
    nfile = socket.recv(256)
    nfile = nfile.decode("utf-8")
    nfile = nfile.rstrip()
    print("received ", nfile)

    data = socket.recv(2048)
    data = data.decode("utf-8")
    data.rstrip()
    print(data)
    print("Data received.")

    file = open(nfile, "w")
    file.write(data)
    # print(data)
    file.close()


print("performing inquiry...")


nearby_devices = bluetooth.discover_devices(lookup_names=True)

print ("found %d devices", len(nearby_devices))
print(nearby_devices)
'''for address in nearby_devices:
    print(address)'''



sock = connect()
print("Please choose the action:")
print("1. Send data");
print("2. Receive data");
print("0. exit");
com = int(input())

if com == 1:
    senddata(sock)
if com == 2:
    recvdata(sock)
